const currentEnv = import.meta.env.VITE_APP_ENV || 'debug'
const directusApiUrl = (import.meta.env.VITE_DIRECTUS_API_URL || 'https://app.ejet-elkahraba.com').replace(/\/$/, '')

export const appConfig = {
  env: currentEnv,
  isDebug: currentEnv !== 'production',
  apiBaseUrl: currentEnv === 'production' ? directusApiUrl : '/api',
  whishBaseUrl: (import.meta.env.VITE_WHISH_BASE_URL || import.meta.env.VITE_DIRECTUS_API_URL || 'https://app.ejet-elkahraba.com').replace(/\/$/, ''),
  paymentToken: import.meta.env.VITE_PAYMENT_API_TOKEN || '',
  debugSmsWebhookEnabled: import.meta.env.VITE_ENABLE_DEBUG_SMS_WEBHOOK === 'true',
  debugWhishSimulationEnabled: import.meta.env.VITE_ENABLE_DEBUG_WHISH_SIMULATION === 'true',
  enableCarrierDetection: import.meta.env.VITE_ENABLE_CARRIER_DETECTION !== 'false',
  showSummaryStep: import.meta.env.VITE_SHOW_PAYMENT_SUMMARY === 'true',
  identity: {
    appName: 'Ejet Elkahraba App',
    portalName: 'Ejet Pay',
    title: 'Renew the Ejet Elkahraba App',
    titleAr: 'جدد اشتراك تطبيق إجت الكهربا',
    subtitle: 'Renew quickly with Whish, phone units, or an activation code.',
    subtitleAr: 'جدد بسرعة عبر Whish أو وحدات الهاتف أو كود التفعيل.',
    logo: '/assets/brand/logo.svg',
    splashLogo: '/assets/brand/logo-splash.svg',
    supportPhone: '+96181554661',
    websiteUrl: 'https://ejet-elkahraba.com',
    whatsappUrl: 'https://wa.me/96181554661',
    appDeepLink: 'ejet://powerline',
    domainHint: 'pay.ejet-elkahraba.com',
  },
  theme: {
    primary: '#FACE0B',
    primaryDark: '#202020',
    primarySoft: '#FFECAB',
    primaryMid: '#FFD868',
    button: '#FFD23C',
    ink: '#202020',
    muted: '#6B6756',
    surface: '#ffffff',
    soft: '#FFF8D7',
    accent: '#31A13B',
    danger: '#C53232',
    warning: '#D99400',
  },
  payment: {
    currency: 'USD',
    promoSource: 'ejet_payment_portal',
    promoUsedFor: 'ejet_subscription',
    statusPollMs: 8000,
    whishVerifyPollMs: 3000,
    whishVerifyTimeoutMs: 120000,
    maxWhishPolls: 40,
    smsWebhookToken: '5gm5ODtpuuNrkUtFr95TbA61wfcxksMF',
    endpoints: {
      plans: (locale) =>
        `/items/plan?fields=id,current_value,previous_value,renew_in_days,sort,tr.name&sort=sort&deep[tr][_filter][languages_code][_eq]=${encodeURIComponent(locale || 'en-US')}`,
      draftPayment: '/items/payment?fields=id,status,amount,amount_collected,user,method,description',
      createWhish: '/pay/whish',
      paymentDetails: (id) =>
        `/items/payment?fields=id,status,amount,amount_collected,validated_at,method,description,payment_link&filter[id][_eq]=${encodeURIComponent(id)}&limit=1`,
      confirmPayment: (id) =>
        `/items/payment/${encodeURIComponent(id)}?fields=id,status,confirmed_at`,
      promoCheck: '/promocode/check/',
      promoConsume: '/promocode/consume/',
      smsWebhook: '/sms-gateway/webhook',
      debugWhishSuccess: (id) => `/payments-callback/debug-success/${encodeURIComponent(id)}`,
    },
    carriers: {
      alfa: {
        id: 'alfa',
        method: 'alfa_units',
        title: 'Alfa units',
        titleAr: 'وحدات ألفا',
        shortCode: '1313',
        receiver: '81554661',
        operator: 'alfa',
        icon: '/assets/payment/alfa.png',
        brandColor: '#ED1C24',
        brandSoft: '#FFF0F1',
        pattern: /^(\+?(961)|0)?(3[1-5]|70[1-5]|71[06-9]|76[1-5]|79[1-4]|81[1-5])\d{4,5}$/,
      },
      touch: {
        id: 'touch',
        method: 'touch_units',
        title: 'Touch units',
        titleAr: 'وحدات تاتش',
        shortCode: '1199',
        receiver: '79013155',
        operator: 'touch',
        icon: '/assets/payment/touch.png',
        brandColor: '#009FBC',
        brandSoft: '#EAFBFE',
        pattern: /^(\+?(961)|0)?(30|3[6-9]|70[06-9]|71[1-5]|76[06-9]|78[7-9]|79[06-9]|81[06-9])\d{4,5}$/,
      },
    },
  },
  firebase: {
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY || '',
    appId: import.meta.env.VITE_FIREBASE_APP_ID || '',
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || '',
  },
  recaptcha: {
    siteKey: import.meta.env.VITE_RECAPTCHA_SITE_KEY || '',
  },
}
