export const appConfig = {
  env: import.meta.env.VITE_APP_ENV || 'debug',
  isDebug: (import.meta.env.VITE_APP_ENV || 'debug') !== 'production',
  apiBaseUrl: (import.meta.env.VITE_DIRECTUS_API_URL || 'https://test.ejet-elkahraba.com').replace(/\/$/, ''),
  whishBaseUrl: (import.meta.env.VITE_WHISH_BASE_URL || import.meta.env.VITE_DIRECTUS_API_URL || 'https://test.ejet-elkahraba.com').replace(/\/$/, ''),
  paymentToken: import.meta.env.VITE_PAYMENT_API_TOKEN || '',
  debugSmsWebhookEnabled: import.meta.env.VITE_ENABLE_DEBUG_SMS_WEBHOOK === 'true',
  identity: {
    appName: 'Smart Ads',
    portalName: 'Smart Ads Pay',
    title: 'Pay for Smart Ads',
    titleAr: 'ادفع لخدمة Smart Ads',
    subtitle: 'Enter the phone used in the app, choose a payment method, and complete the payment.',
    subtitleAr: 'أدخل رقم الهاتف المستخدم في التطبيق، اختر طريقة الدفع، ثم أكمل العملية.',
    logo: '/assets/brand/logo.webp',
    splashLogo: '/assets/brand/logo-splash.webp',
    supportPhone: '+96181554661',
    domainHint: 'pay.smartads-lb.com',
  },
  theme: {
    primary: '#21C063',
    primaryDark: '#16A653',
    ink: '#182326',
    muted: '#60706b',
    surface: '#ffffff',
    soft: '#eff8f1',
    accent: '#008069',
    danger: '#C53232',
    warning: '#E9A317',
  },
  payment: {
    currency: 'USD',
    monthlyPrice: 3,
    promoSource: 'smart_ads_payment_portal',
    promoUsedFor: 'smart_ads_upgrade',
    statusPollMs: 5000,
    whishPollMs: 4000,
    maxWhishPolls: 30,
    smsWebhookToken: '5gm5ODtpuuNrkUtFr95TbA61wfcxksMF',
    endpoints: {
      bundles: '/items/bundles?fields=id,amount,credits&sort=amount',
      draftPayment: '/items/payment?fields=id,status,amount,amount_collected,payment_link',
      createWhish: '/pay/whish',
      paymentDetails: (id) => `/items/payment/${encodeURIComponent(id)}?fields=id,status,method,amount,amount_collected,validated_at,payment_link,confirmed_at`,
      whishLink: (id) => `/items/payment/${encodeURIComponent(id)}?fields=id,status,amount,amount_collected,payment_link`,
      promoConsume: '/promocode/consume/',
      smsWebhook: '/sms-gateway/webhook',
    },
    carriers: {
      alfa: {
        id: 'alfa',
        method: 'alfa_units',
        title: 'Alfa credit',
        titleAr: 'رصيد ألفا',
        shortCode: '1313',
        receiver: '81554661',
        operator: 'alfa',
        icon: '/assets/payment/alfa.webp',
      },
      touch: {
        id: 'touch',
        method: 'touch_units',
        title: 'Touch units',
        titleAr: 'رصيد تاتش',
        shortCode: '1199',
        receiver: '79013155',
        operator: 'touch',
        icon: '/assets/payment/touch.webp',
      },
    },
  },
  firebase: {
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY || '',
    appId: import.meta.env.VITE_FIREBASE_APP_ID || '',
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || '',
  },
}
